// react/sportsstore/src/shop/CartSummary.js
import React, {Component} from "react";
import {Link} from "react-router-dom";

export class CartSummary extends Component {
  getSummary = () => {
    if (this.props.cartItems > 0) {
      return <span>
                {this.props.cartItems} item(s),
                ${this.props.cartPrice.toFixed(2)}
            </span>
    } else {
      return <span>Your cart: (empty) </span>
    }
  }

  getLinkClasses = () => {
    return `btn btn-sm bg-dark text-white ${this.props.cartItems === 0 ? "disabled" : ""}`;
  }

  render() {
    return <div className="float-right">
      <small>
        {this.getSummary()}
        <Link className={this.getLinkClasses()} to="/shop/cart">
          <i className="fa fa-shopping-cart"></i> </Link>
      </small>
    </div>
  }
}

// vue/sportsstore/src/components/CartSummary.vue
<template>
    <div class="float-right">
        <small>
            Your cart:
            <span v-if="itemCount > 0">{{ itemCount }} item(s) {{ totalPrice | currency }}</span>
            <span v-else>
                (empty)
            </span>
        </small>
        <router-link to="/cart" class="btn btn-sm bg-dark text-white"
                     v-bind:disabled="itemCount == 0"><i class="fa fa-shopping-cart"></i>
        </router-link>
    </div>
</template>
<script>
    import {mapGetters} from 'vuex';

    export default {
        computed: {
            ...mapGetters({
                itemCount: "cart/itemCount", totalPrice: "cart/totalPrice"
            })
        }
    } </script>
