// react/sportsstore/src/shop/ProductList.js
import React, {Component} from "react";

export class ProductList extends Component {
    render() {
        if (this.props.products == null || this.props.products.length === 0) {
            return <h5 className="p-2">No Products</h5>
        }
        return this.props.products.map(p =>
            <div className="card m-1 p-1 bg-light" key={p.id}>
                <h4>
                    {p.name}
                    <span className="badge badge-pill badge-primary float-right"> ${p.price.toFixed(2)} </span>
                </h4>
                <div className="card-text bg-white p-1"> {p.description}</div>
            </div>
        )
    }
}

// vue/sportsstore/src/components/ProductList.vue
<template>
    <div>
        <div v-for="p in products" v-bind:key="p.id" class="card m-1 p-1 bg-light">
            <h4>
                {{p.name}}
                <span class="badge badge-pill badge-primary float-right">{{ p.price | currency }} </span>
            </h4>
            <div class="card-text bg-white p-1">{{ p.description }}</div>
        </div>
        <page-controls/>
    </div>
</template>
<script>
    import {mapGetters} from "vuex";
    import PageControls from "./PageControls";

    export default {
        components: {PageControls},
        computed: {
            ...mapGetters({products: "processedProducts"})
        },
        filters: {
            currency(value) {
                return new Intl.NumberFormat("en-US",
                    {style: "currency", currency: "USD"}).format(value);
            }
        }
    }
</script>
