// vue/sportsstore/src/components/admin/Admin.vue
<template>
    <div class="container-fluid">
        <div class="row">
            <div class="col bg-secondary text-white">
                <a class="navbar-brand">SPORTS STORE Admin</a>
            </div>
        </div>
        <div class="row">
            <div class="col-3 bg-secondary p-2">
                <router-link to="/admin/products" class="btn btn-block btn-primary" active-class="active">
                    Products
                </router-link>
                <router-link to="/admin/orders" class="btn btn-block btn-primary" active-class="active">
                    Orders
                </router-link>
            </div>
            <div class="col-9 p-2">
                <router-view/>
            </div>
        </div>
    </div>
</template>

// react/sportsstore/src/admin/Admin.js
import React, {Component} from "react";
import ApolloClient from "apollo-boost";
import {ApolloProvider} from "react-apollo";
import {GraphQlUrl} from "../data/Urls";
import {OrdersConnector} from "./OrdersConnector"

const graphQlClient = new ApolloClient({
  uri: GraphQlUrl
});

export class Admin extends Component {

  render() {
    return <ApolloProvider client={graphQlClient}>
      <div className="container-fluid">
        <div className="row">
          <div className="col bg-info text-white">
            <div className="navbar-brand">SPORTS STORE</div>
          </div>
        </div>
        <div className="row">
          <div className="col p-2"><OrdersConnector/>
          </div>
        </div>
      </div>
    </ApolloProvider>
  }
}
